### ISSUE TITLE
JRE is not working on GitPod

### ISSUE THREAD

**Issue by amelia2802** [amelia2802/App-of-Requirements#17]

**Comment by Hirdey-1999** [comment]
I Can Help To Resolve This Issue

**Comment by amelia2802** [comment]
> I Can Help To Resolve This Issue

Thank you for showing interest in the App of Requirements 😀 I've assigned you. Have a nice day! 😊

**Comment by Hirdey-1999** [comment]
I Am Able To Access The Website Using The GitPod When I Downloaded The JDK in the GitPod but There is A issue check for This 
![image](https://user-images.githubusercontent.com/71271612/186442832-bc888c91-2696-4b55-b4d6-7eaf77ca5ebb.png)

**Comment by amelia2802** [comment]
> I Am Able To Access The Website Using The GitPod When I Downloaded The JDK in the GitPod but There is A issue check for This ![image](https://user-images.githubusercontent.com/71271612/186442832-bc888c91-2696-4b55-b4d6-7eaf77ca5ebb.png)

Can you share the picture of the terminal after you run it? look for the lines  ```No mapping found for /xyz file```  something like that...

**Comment by amelia2802** [comment]
> I Can Help To Resolve This Issue

- After running the application go to the ```ports`` nav below the editor and beside the terminal nav. 
- Copy the address which is similar to this ``` https://8080-amelia2802-appofrequire-im5iow4dozr.ws-us63.gitpod.io ```
-  Add ``` /welcomehome ``` after the address, now it will be like this ``` https://8080-amelia2802-appofrequire-im5iow4dozr.ws-us63.gitpod.io/welcomehome ```
-  Previous images of the welcome page are removed so you can't see any picture there, click on the login for student option

I hope it will fix your problem

**Comment by Hirdey-1999** [comment]
The JRE is Working On GitPod Should I Push The Changes 
![image](https://user-images.githubusercontent.com/71271612/186634812-6dc43aee-9eef-4340-9d1d-78dc4d7fec75.png)

**Comment by amelia2802** [comment]
Yes you can

**Comment by Hirdey-1999** [comment]
https://amelia2802-appofrequire-5dg735fz9wm.ws-us63.gitpod.io/ actually i have created a dockerfile and yaml file for java to work in gitpod but i am unable to create a merge request can you help me

**Comment by arghadip23** [comment]
> https://amelia2802-appofrequire-5dg735fz9wm.ws-us63.gitpod.io/ actually i have created a dockerfile and yaml file for java to work in gitpod but i am unable to create a merge request can you help me

Provide a snap of the problem, so we can understand the problem better.

**Comment by Hirdey-1999** [comment]
Made The Changes Please Check And Merge https://github.com/amelia2802/App-of-Requirements/pull/30
