### ISSUE TITLE
CodeQl showing runtime error for analyzing java

### ISSUE THREAD

**Issue by amelia2802** [amelia2802/App-of-Requirements#23]

**Comment by abhie16** [comment]
![image](https://user-images.githubusercontent.com/95357648/182665408-1d7e53d3-58b0-49f4-8ded-20f355fc6db8.png)

found in docs , editing workflow may solve this issue.
I found that we may remove autobuild for java and  manually add build steps.
In img there is a example of same

**Comment by abhie16** [comment]
please assign me to solve this, thank you

**Comment by abhie16** [comment]
![image](https://user-images.githubusercontent.com/95357648/183035945-8c334aa9-6f28-4087-a491-630c37ee14a9.png)

can you pls check java code , it is showing error in it
