### ISSUE TITLE
Suggest a LOGO

### ISSUE THREAD

**Issue by amelia2802** [amelia2802/App-of-Requirements#27]

**Comment by WaburiBK** [comment]
Hey let me work on this

**Comment by amelia2802** [comment]
> Hey let me work on this

Thank you for showing interest in the App of Requirements 😀You don't have to assign yourself for this issue. You can share your suggestion here or in the discussion forum. Have a nice day! 😊

**Comment by abhie16** [comment]
![contri-logo](https://user-images.githubusercontent.com/95357648/186651318-55287669-7a76-46df-bc13-9b11640a1a5a.png)
